language: python
python:
    - 3.5
sudo: false
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
install:
    - pip install tox
script:
    - tox
notifications:
    email: false
